-- BrProject Phase 5 Flyway baseline (clean)
-- PostgreSQL baseline generated from the MariaDB schema; vendor-specific types and indexes normalized.
-- Regenerated by tools/generate_flyway_migrations.py


-- ========== accounts.sql ==========
CREATE TABLE IF NOT EXISTS accounts (
 	login VARCHAR(45) NOT NULL DEFAULT '',
 	password VARCHAR(60) NOT NULL DEFAULT '',
 	last_active BIGINT NOT NULL DEFAULT 0,
 	access_level INTEGER NOT NULL DEFAULT 0,
 	last_server INTEGER NOT NULL DEFAULT 1,
 	PRIMARY KEY (login)
);
-- ========== account_premium.sql ==========
CREATE TABLE IF NOT EXISTS account_premium (
  account_name varchar(45) NOT NULL DEFAULT '',
  premium_service INTEGER NOT NULL DEFAULT '0',
  enddate decimal(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (account_name)
);
-- ========== gameservers.sql ==========
CREATE TABLE IF NOT EXISTS gameservers (
  server_id INTEGER NOT NULL default '0',
  hexid varchar(50) NOT NULL default '',
  host varchar(50) NOT NULL default '',
  PRIMARY KEY (server_id)
);
-- ========== characters.sql ==========
CREATE TABLE IF NOT EXISTS characters (
  account_name VARCHAR(45) DEFAULT NULL,
  obj_Id INT NOT NULL DEFAULT 0,
  char_name VARCHAR(35) NOT NULL,
  level SMALLINT DEFAULT NULL,
  maxHp INTEGER DEFAULT NULL,
  curHp INTEGER DEFAULT NULL,
  maxCp INTEGER DEFAULT NULL,
  curCp INTEGER DEFAULT NULL,
  maxMp INTEGER DEFAULT NULL,
  curMp INTEGER DEFAULT NULL,
  face SMALLINT DEFAULT NULL,
  hairStyle SMALLINT DEFAULT NULL,
  hairColor SMALLINT DEFAULT NULL,
  sex SMALLINT DEFAULT NULL,
  heading INTEGER DEFAULT NULL,
  x INTEGER DEFAULT NULL,
  y INTEGER DEFAULT NULL,
  z INTEGER DEFAULT NULL,
  exp BIGINT DEFAULT 0,
  expBeforeDeath BIGINT DEFAULT 0,
  sp INT NOT NULL DEFAULT 0,
  karma INT DEFAULT NULL,
  pvpkills SMALLINT DEFAULT NULL,
  pkkills SMALLINT DEFAULT NULL,
  clanid INT DEFAULT NULL,
  race SMALLINT DEFAULT NULL,
  classid SMALLINT DEFAULT NULL,
  base_class SMALLINT NOT NULL DEFAULT 0,
  deletetime BIGINT DEFAULT NULL,
  title VARCHAR(16) DEFAULT NULL,
  rec_have SMALLINT NOT NULL DEFAULT 0,
  rec_left SMALLINT NOT NULL DEFAULT 0,
  accesslevel INTEGER DEFAULT 0,
  online SMALLINT DEFAULT NULL,
  onlinetime INT DEFAULT NULL,
  lastAccess BIGINT DEFAULT NULL,
  wantspeace SMALLINT DEFAULT 0,
  isin7sdungeon SMALLINT NOT NULL DEFAULT 0,
  punish_level SMALLINT NOT NULL DEFAULT 0,
  punish_timer BIGINT NOT NULL DEFAULT 0,
  power_grade SMALLINT DEFAULT NULL,
  nobless SMALLINT NOT NULL DEFAULT 0,
  hero SMALLINT NOT NULL DEFAULT 0,
  subpledge SMALLINT NOT NULL DEFAULT 0,
  lvl_joined_academy SMALLINT NOT NULL DEFAULT 0,
  apprentice INT NOT NULL DEFAULT 0,
  sponsor INT NOT NULL DEFAULT 0,
  varka_ketra_ally SMALLINT NOT NULL DEFAULT 0,
  clan_join_expiry_time BIGINT NOT NULL DEFAULT 0,
  clan_create_expiry_time BIGINT NOT NULL DEFAULT 0,
  death_penalty_level SMALLINT NOT NULL DEFAULT 0,
  herountil BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (obj_Id)
);
-- ========== character_recommends.sql ==========
CREATE TABLE IF NOT EXISTS character_recommends ( 
 char_id INT NOT NULL default 0, 
 target_id INTEGER NOT NULL DEFAULT 0, 
 PRIMARY KEY (char_id,target_id) 
);
-- ========== character_skills_save.sql ==========
CREATE TABLE IF NOT EXISTS character_skills_save (
  char_obj_id INT NOT NULL default 0,
  skill_id INT NOT NULL default 0,
  skill_level INTEGER NOT NULL default 1,
  effect_count INT NOT NULL default 0,
  effect_cur_time INT NOT NULL default 0,
  reuse_delay INTEGER NOT NULL DEFAULT 0,
  systime BIGINT NOT NULL DEFAULT 0,
  restore_type INTEGER NOT NULL DEFAULT 0,
  class_index INTEGER NOT NULL DEFAULT 0,
  buff_index INTEGER NOT NULL default 0,
  npc INTEGER NOT NULL default 0,
  PRIMARY KEY (char_obj_id,skill_id,skill_level,class_index)
);
-- ========== character_quests.sql ==========
CREATE TABLE IF NOT EXISTS character_quests (
  charId INT NOT NULL DEFAULT 0,
  name VARCHAR(40) NOT NULL DEFAULT '',
  var VARCHAR(20) NOT NULL DEFAULT '',
  value VARCHAR(255),
  PRIMARY KEY  (charId,name,var)
);
-- ========== character_mission.sql ==========
CREATE TABLE IF NOT EXISTS character_mission (
  object_id INTEGER NOT NULL,
  type VARCHAR(50) NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  value INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (object_id, type)
);
-- ========== character_hennas.sql ==========
CREATE TABLE IF NOT EXISTS character_hennas (
  char_obj_id INT NOT NULL DEFAULT 0,
  symbol_id INT,
  slot INT NOT NULL DEFAULT 0,
  class_index INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (char_obj_id,slot,class_index)
);
-- ========== character_subclasses.sql ==========
CREATE TABLE IF NOT EXISTS character_subclasses (
char_obj_id decimal(11,0) NOT NULL default '0',
class_id INTEGER NOT NULL default '0',
exp decimal(20,0) NOT NULL default '0',
sp decimal(11,0) NOT NULL default '0',
level INTEGER NOT NULL default '40',
class_index INTEGER NOT NULL default '0',
PRIMARY KEY  (char_obj_id,class_id)
);
-- ========== character_shortcuts.sql ==========
CREATE TABLE IF NOT EXISTS character_shortcuts (
  char_obj_id INT NOT NULL DEFAULT 0,
  slot SMALLINT NOT NULL DEFAULT 0,
  page SMALLINT NOT NULL DEFAULT 0,
  type VARCHAR(6) NOT NULL DEFAULT 'NONE',
  id INT NOT NULL DEFAULT 0,
  level SMALLINT NOT NULL DEFAULT 0,
  class_index SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (char_obj_id,slot,page,class_index)
);
-- ========== character_memo.sql ==========
CREATE TABLE IF NOT EXISTS character_memo (
  charId INTEGER NOT NULL,
  var VARCHAR(255) NOT NULL,
  val TEXT NOT NULL,
  PRIMARY KEY (charId, var)
);
-- ========== character_recipebook.sql ==========
CREATE TABLE IF NOT EXISTS character_recipebook (
  charId INT NOT NULL DEFAULT 0,
  recipeId SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (charId,recipeId)
);
-- ========== character_raid_points.sql ==========
CREATE TABLE IF NOT EXISTS character_raid_points (
  char_id INT NOT NULL DEFAULT 0,
  boss_id INT NOT NULL DEFAULT 0,
  points INT NOT NULL DEFAULT 0,
  PRIMARY KEY (char_id,boss_id)
);
-- ========== character_macroses.sql ==========
CREATE TABLE IF NOT EXISTS character_macroses (
  char_obj_id INT NOT NULL DEFAULT 0,
  id INT NOT NULL DEFAULT 0,
  icon INT,
  name VARCHAR(40) ,
  descr VARCHAR(80) ,
  acronym VARCHAR(4) ,
  commands VARCHAR(500) ,
  PRIMARY KEY (char_obj_id,id)
);
-- ========== character_data.sql ==========
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS character_data (
  charId INTEGER NOT NULL,
  valueName varchar(32) NOT NULL,
  valueData varchar(250) DEFAULT NULL,
  PRIMARY KEY (charId,valueName)
);
-- ========== character_relations.sql ==========
CREATE TABLE IF NOT EXISTS character_relations (
  char_id INT NOT NULL default 0,
  friend_id INT NOT NULL DEFAULT 0,
  relation INT NOT NULL DEFAULT 0,
  PRIMARY KEY (char_id,friend_id)
);
-- ========== character_skills.sql ==========
CREATE TABLE IF NOT EXISTS character_skills (
  char_obj_id INT NOT NULL default 0,
  skill_id INT NOT NULL default 0,
  skill_level INTEGER NOT NULL default 1,
  class_index INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (char_obj_id,skill_id,class_index)
);
-- ========== items.sql ==========
CREATE TABLE IF NOT EXISTS items (
  owner_id INT,
  object_id INT NOT NULL DEFAULT 0,
  item_id SMALLINT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  enchant_level SMALLINT NOT NULL DEFAULT 0,
  loc VARCHAR(10),
  loc_data INT,
  custom_type1 INT NOT NULL DEFAULT 0,
  custom_type2 INT NOT NULL DEFAULT 0,
  mana_left INT NOT NULL DEFAULT -1,
  time BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (object_id)
);
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS items_delayed (
  owner_id INTEGER NOT NULL,
  item_id SMALLINT NOT NULL,
  count INTEGER NOT NULL DEFAULT '1',
  enchant_level SMALLINT NOT NULL DEFAULT '0',
  payment_status SMALLINT NOT NULL DEFAULT '0',
  description varchar(255) DEFAULT NULL
);
-- ========== items_on_ground.sql ==========
CREATE TABLE IF NOT EXISTS items_on_ground (
  object_id INTEGER NOT NULL default '0',
  item_id INTEGER default NULL,
  count INTEGER default NULL,
  enchant_level INTEGER default NULL,
  x INTEGER default NULL,
  y INTEGER default NULL,
  z INTEGER default NULL,
  time decimal(20,0) default NULL,
  PRIMARY KEY  (object_id)
);
-- ========== pets.sql ==========
CREATE TABLE IF NOT EXISTS pets (
  item_obj_id decimal(11) NOT NULL default 0,
  name varchar(16),
  level decimal(11),
  curHp decimal(18,0),
  curMp decimal(18,0),
  exp decimal(20, 0),
  sp decimal(11),
  fed decimal(11),
  PRIMARY KEY (item_obj_id)
);
-- ========== augmentations.sql ==========
CREATE TABLE IF NOT EXISTS augmentations (
	item_oid INT NOT NULL DEFAULT 0,
	attributes INT NOT NULL DEFAULT -1,
	skill_id INT NOT NULL DEFAULT -1,
	skill_level INT NOT NULL DEFAULT -1,
	PRIMARY KEY (item_oid)
);
-- ========== cursed_weapons.sql ==========
CREATE TABLE IF NOT EXISTS cursed_weapons (
  itemId INT,
  playerId INT DEFAULT 0,
  playerKarma INT DEFAULT 0,
  playerPkKills INT DEFAULT 0,
  nbKills INT DEFAULT 0,
  currentStage INT DEFAULT 0,
  numberBeforeNextStage INT DEFAULT 0,
  hungryTime INT DEFAULT 0,
  endTime DECIMAL(20,0) DEFAULT 0,
  PRIMARY KEY (itemId)
);
-- ========== clan_data.sql ==========
CREATE TABLE IF NOT EXISTS clan_data (
  clan_id INT NOT NULL DEFAULT 0,
  clan_name VARCHAR(20),
  clan_level INT NOT NULL DEFAULT 0,
  reputation_score INT NOT NULL DEFAULT 0,
  hasCastle SMALLINT NOT NULL DEFAULT 0,
  ally_id INT NOT NULL DEFAULT 0,
  ally_name VARCHAR(20),
  leader_id INT NOT NULL DEFAULT 0,
  new_leader_id INT NOT NULL DEFAULT 0,
  crest_id INT NOT NULL DEFAULT 0,
  crest_large_id INT NOT NULL DEFAULT 0,
  ally_crest_id INT NOT NULL DEFAULT 0,
  auction_bid_at INT NOT NULL DEFAULT 0,
  ally_penalty_expiry_time BIGINT NOT NULL DEFAULT 0,
  ally_penalty_type INT NOT NULL DEFAULT 0,
  char_penalty_expiry_time BIGINT NOT NULL DEFAULT 0,
  dissolving_expiry_time BIGINT NOT NULL DEFAULT 0,
  enabled SMALLINT NOT NULL DEFAULT 0,
  notice TEXT,
  introduction TEXT,
  graduates TEXT,
  PRIMARY KEY (clan_id)
);
-- ========== clanhall_flagwar_attackers.sql ==========
CREATE TABLE IF NOT EXISTS clanhall_flagwar_attackers (
  clanhall_id SMALLINT NOT NULL DEFAULT '0',
  flag INTEGER NOT NULL DEFAULT '0',
  npc INTEGER NOT NULL DEFAULT '0',
  clan_id INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (flag)
);
-- ========== clan_privs.sql ==========
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS clan_privs (
  clan_id INT NOT NULL DEFAULT'0',
  ranking INT NOT NULL DEFAULT '0',
  privs INT NOT NULL DEFAULT '0',
  PRIMARY KEY (clan_id,ranking)
);
-- ========== clan_skills.sql ==========
CREATE TABLE IF NOT EXISTS clan_skills (
  clan_id INT NOT NULL DEFAULT 0,
  skill_id INT NOT NULL DEFAULT 0,
  skill_level INT NOT NULL DEFAULT 0,
  PRIMARY KEY (clan_id,skill_id)
);
-- ========== clanhall_flagwar_members.sql ==========
CREATE TABLE IF NOT EXISTS clanhall_flagwar_members (
  clanhall_id SMALLINT NOT NULL DEFAULT '0',
  clan_id INTEGER NOT NULL DEFAULT '0',
  object_id INTEGER NOT NULL DEFAULT '0'
);
-- ========== clan_subpledges.sql ==========
CREATE TABLE IF NOT EXISTS clan_subpledges (
  clan_id INT NOT NULL default '0',
  sub_pledge_id INT NOT NULL default '0',
  name varchar(45),
  leader_id INT NOT NULL default '0',
  PRIMARY KEY (clan_id,sub_pledge_id)
);
-- ========== clanhall_flagwar_owner_npcs.sql ==========
CREATE TABLE IF NOT EXISTS clanhall_flagwar_owner_npcs (
  clanhall_id SMALLINT NOT NULL DEFAULT '0',
  npc_id INTEGER NOT NULL DEFAULT '0',
  clan_id INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY (clanhall_id)
);
-- ========== clan_wars.sql ==========
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS clan_wars (
  clan1 varchar(35) NOT NULL DEFAULT '',
  clan2 varchar(35) NOT NULL DEFAULT '',
  expiry_time decimal(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (clan1,clan2)
);
-- ========== clanhall_siege_attackers.sql ==========
CREATE TABLE IF NOT EXISTS clanhall_siege_attackers (
  clanhall_id SMALLINT NOT NULL DEFAULT '0',
  attacker_id INT NOT NULL DEFAULT '0',
  PRIMARY KEY (clanhall_id, attacker_id)
);
-- ========== clanhall.sql ==========
CREATE TABLE IF NOT EXISTS clanhall (
  id SMALLINT NOT NULL DEFAULT '0',
  ownerId INT NOT NULL DEFAULT '0',
  paidUntil BIGINT NOT NULL DEFAULT '0',
  paid SMALLINT NOT NULL DEFAULT '0',
  sellerBid INT NOT NULL DEFAULT '0',
  sellerName VARCHAR(20) NOT NULL DEFAULT '',
  sellerClanName VARCHAR(20) NOT NULL DEFAULT '',
  endDate BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);
INSERT INTO clanhall VALUES
('21', '0', '0', '0', '0', '', '', '0'),
('22', '0', '0', '0', '0', '', '', '0'),
('23', '0', '0', '0', '0', '', '', '0'),
('24', '0', '0', '0', '0', '', '', '0'),
('25', '0', '0', '0', '0', '', '', '0'),
('26', '0', '0', '0', '0', '', '', '0'),
('27', '0', '0', '0', '0', '', '', '0'),
('28', '0', '0', '0', '0', '', '', '0'),
('29', '0', '0', '0', '0', '', '', '0'),
('30', '0', '0', '0', '0', '', '', '0'),
('31', '0', '0', '0', '0', '', '', '0'),
('32', '0', '0', '0', '0', '', '', '0'),
('33', '0', '0', '0', '0', '', '', '0'),
('34', '0', '0', '0', '0', '', '', '0'),
('35', '0', '0', '0', '0', '', '', '0'),
('36', '0', '0', '0', '0', '', '', '0'),
('37', '0', '0', '0', '0', '', '', '0'),
('38', '0', '0', '0', '0', '', '', '0'),
('39', '0', '0', '0', '0', '', '', '0'),
('40', '0', '0', '0', '0', '', '', '0'),
('41', '0', '0', '0', '0', '', '', '0'),
('42', '0', '0', '0', '0', '', '', '0'),
('43', '0', '0', '0', '0', '', '', '0'),
('44', '0', '0', '0', '0', '', '', '0'),
('45', '0', '0', '0', '0', '', '', '0'),
('46', '0', '0', '0', '0', '', '', '0'),
('47', '0', '0', '0', '0', '', '', '0'),
('48', '0', '0', '0', '0', '', '', '0'),
('49', '0', '0', '0', '0', '', '', '0'),
('50', '0', '0', '0', '0', '', '', '0'),
('51', '0', '0', '0', '0', '', '', '0'),
('52', '0', '0', '0', '0', '', '', '0'),
('53', '0', '0', '0', '0', '', '', '0'),
('54', '0', '0', '0', '0', '', '', '0'),
('55', '0', '0', '0', '0', '', '', '0'),
('56', '0', '0', '0', '0', '', '', '0'),
('57', '0', '0', '0', '0', '', '', '0'),
('58', '0', '0', '0', '0', '', '', '0'),
('59', '0', '0', '0', '0', '', '', '0'),
('60', '0', '0', '0', '0', '', '', '0'),
('61', '0', '0', '0', '0', '', '', '0'),
('62', '0', '0', '0', '0', '', '', '0'),
('63', '0', '0', '0', '0', '', '', '0'),
('64', '0', '0', '0', '0', '', '', '0');

-- ========== clanhall_functions.sql ==========
CREATE TABLE IF NOT EXISTS clanhall_functions (
  hall_id INTEGER NOT NULL default '0',
  type INTEGER NOT NULL default '0',
  lvl INTEGER NOT NULL default '0',
  lease INTEGER NOT NULL default '0',
  rate decimal(20,0) NOT NULL default '0',
  endTime decimal(20,0) NOT NULL default '0',
  PRIMARY KEY (hall_id,type)
);
-- ========== castle_manor_procure.sql ==========
CREATE TABLE IF NOT EXISTS castle_manor_procure (
 castle_id SMALLINT NOT NULL DEFAULT '0',
 crop_id INTEGER NOT NULL DEFAULT '0',
 amount INTEGER NOT NULL DEFAULT '0',
 start_amount INTEGER NOT NULL DEFAULT '0',
 price INTEGER NOT NULL DEFAULT '0',
 reward_type SMALLINT NOT NULL DEFAULT '0',
 next_period SMALLINT NOT NULL DEFAULT '1',
  PRIMARY KEY (castle_id,crop_id,next_period)
);
-- ========== castle_doorupgrade.sql ==========
CREATE TABLE IF NOT EXISTS castle_doorupgrade (
  doorId INT NOT NULL DEFAULT 0,
  hp SMALLINT NOT NULL DEFAULT 0,
  castleId SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (doorId)
);
-- ========== castle_trapupgrade.sql ==========
CREATE TABLE IF NOT EXISTS castle_trapupgrade (
  castleId SMALLINT NOT NULL DEFAULT '0',
  towerIndex SMALLINT NOT NULL DEFAULT '0',
  level SMALLINT NOT NULL DEFAULT '0',
  PRIMARY KEY (towerIndex,castleId)
);
-- ========== castle.sql ==========
CREATE TABLE IF NOT EXISTS castle (
  id INT NOT NULL DEFAULT '0',
  currentTaxPercent INT NOT NULL DEFAULT '0',
  nextTaxPercent INT NOT NULL DEFAULT '0',
  treasury BIGINT NOT NULL DEFAULT '0',
  taxRevenue BIGINT NOT NULL DEFAULT '0',
  seedIncome BIGINT NOT NULL DEFAULT '0',
  siegeDate DECIMAL(20,0) NOT NULL DEFAULT '0',
  regTimeOver VARCHAR(32) DEFAULT 'true' NOT NULL,
  certificates SMALLINT NOT NULL DEFAULT '300',
  PRIMARY KEY (id)
);
INSERT INTO castle VALUES
(1,15,15,0,0,0,0,'true',300),
(2,15,15,0,0,0,0,'true',300),
(3,15,15,0,0,0,0,'true',300),
(4,15,15,0,0,0,0,'true',300),
(5,15,15,0,0,0,0,'true',300),
(6,15,15,0,0,0,0,'true',300),
(7,15,15,0,0,0,0,'true',300),
(8,15,15,0,0,0,0,'true',300),
(9,15,15,0,0,0,0,'true',300);

-- ========== castle_manor_production.sql ==========
CREATE TABLE IF NOT EXISTS castle_manor_production (
 castle_id SMALLINT NOT NULL DEFAULT '0',
 seed_id INTEGER NOT NULL DEFAULT '0',
 amount INTEGER NOT NULL DEFAULT '0',
 start_amount INTEGER NOT NULL DEFAULT '0',
 price INTEGER NOT NULL DEFAULT '0',
 next_period SMALLINT NOT NULL DEFAULT '1',
 PRIMARY KEY (castle_id, seed_id, next_period)
);
-- ========== castle_functions.sql ==========
CREATE TABLE IF NOT EXISTS castle_functions (
  castle_id INTEGER NOT NULL default '0',
  type INTEGER NOT NULL default '0',
  lvl INTEGER NOT NULL default '0',
  lease INTEGER NOT NULL default '0',
  rate decimal(20,0) NOT NULL default '0',
  endTime BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (castle_id,type)
);
-- ========== siege_clans.sql ==========
CREATE TABLE IF NOT EXISTS siege_clans (
   castle_id SMALLINT NOT NULL DEFAULT '0',
   clan_id INTEGER NOT NULL DEFAULT '0',
   type VARCHAR(8) DEFAULT 'PENDING',
   PRIMARY KEY (castle_id, clan_id)
);
-- ========== spawn_data.sql ==========
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS spawn_data (
  name VARCHAR(80) NOT NULL,
  status SMALLINT NOT NULL,
  current_hp INT NOT NULL,
  current_mp INT NOT NULL,
  loc_x INT NOT NULL DEFAULT 0,
  loc_y INT NOT NULL DEFAULT 0,
  loc_z INT NOT NULL DEFAULT 0,
  heading INTEGER NOT NULL DEFAULT 0,
  db_value SMALLINT NOT NULL DEFAULT 0,
  respawn_time BIGINT NOT NULL default 0,
  PRIMARY KEY (name)
);
-- ========== olympiad_nobles_eom.sql ==========
CREATE TABLE IF NOT EXISTS olympiad_nobles_eom (
  char_id INT NOT NULL default 0,
  class_id SMALLINT NOT NULL default 0,
  olympiad_points INTEGER NOT NULL default 0,
  competitions_done SMALLINT NOT NULL default 0,
  competitions_won SMALLINT NOT NULL default 0,
  competitions_lost SMALLINT NOT NULL default 0,
  competitions_drawn SMALLINT NOT NULL default 0,
  PRIMARY KEY (char_id)
);
-- ========== olympiad_fights.sql ==========
CREATE TABLE IF NOT EXISTS olympiad_fights (
  charOneId INTEGER NOT NULL,
  charTwoId INTEGER NOT NULL,
  charOneClass SMALLINT NOT NULL default '0',
  charTwoClass SMALLINT NOT NULL default '0',
  winner SMALLINT NOT NULL default '0',
  start BIGINT NOT NULL DEFAULT '0',
  time BIGINT NOT NULL DEFAULT '0',
  classed SMALLINT NOT NULL default '0'
);
-- ========== olympiad_data.sql ==========
CREATE TABLE IF NOT EXISTS olympiad_data (
  id SMALLINT NOT NULL DEFAULT '0',
  current_cycle INTEGER NOT NULL DEFAULT '1',
  period VARCHAR(12) NOT NULL DEFAULT 'COMPETITION',
  olympiad_end BIGINT NOT NULL DEFAULT '0',
  validation_end BIGINT NOT NULL DEFAULT '0',
  next_weekly_change BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);
-- ========== olympiad_nobles.sql ==========
CREATE TABLE IF NOT EXISTS olympiad_nobles (
  char_id INT NOT NULL default 0,
  class_id SMALLINT NOT NULL default 0,
  olympiad_points INTEGER NOT NULL default 0,
  competitions_done SMALLINT NOT NULL default 0,
  competitions_won SMALLINT NOT NULL default 0,
  competitions_lost SMALLINT NOT NULL default 0,
  competitions_drawn SMALLINT NOT NULL default 0,
  PRIMARY KEY (char_id)
);
-- ========== seven_signs_festival.sql ==========
CREATE TABLE IF NOT EXISTS seven_signs_festival (
festivalId INTEGER NOT NULL DEFAULT '0',
cabal varchar(4) NOT NULL DEFAULT '',
cycle INTEGER NOT NULL DEFAULT '0',
date BIGINT DEFAULT '0',
score INTEGER NOT NULL DEFAULT '0',
members varchar(255) NOT NULL DEFAULT '',
PRIMARY KEY (festivalId,cabal,cycle)
);
INSERT INTO seven_signs_festival VALUES 
(0, 'DAWN', 1, 0, 0, ''),
(1, 'DAWN', 1, 0, 0, ''),
(2, 'DAWN', 1, 0, 0, ''),
(3, 'DAWN', 1, 0, 0, ''),
(4, 'DAWN', 1, 0, 0, ''),
(0, 'DUSK', 1, 0, 0, ''),
(1, 'DUSK', 1, 0, 0, ''),
(2, 'DUSK', 1, 0, 0, ''),
(3, 'DUSK', 1, 0, 0, ''),
(4, 'DUSK', 1, 0, 0, '');

-- ========== seven_signs_status.sql ==========
CREATE TABLE IF NOT EXISTS seven_signs_status (
  id INTEGER NOT NULL default '0',
  current_cycle INTEGER NOT NULL DEFAULT '1',
  festival_cycle INTEGER NOT NULL DEFAULT '1',
  active_period VARCHAR(16) NOT NULL DEFAULT 'COMPETITION',
  date BIGINT NOT NULL DEFAULT '0',
  previous_winner VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
  dawn_stone_score DECIMAL(20,0) NOT NULL DEFAULT '0',
  dawn_festival_score INTEGER NOT NULL DEFAULT '0',
  dusk_stone_score DECIMAL(20,0) NOT NULL DEFAULT '0',
  dusk_festival_score INTEGER NOT NULL DEFAULT '0',
  avarice_owner VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
  gnosis_owner VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
  strife_owner VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
  avarice_dawn_score INTEGER NOT NULL DEFAULT '0',
  gnosis_dawn_score INTEGER NOT NULL DEFAULT '0',
  strife_dawn_score INTEGER NOT NULL DEFAULT '0',
  avarice_dusk_score INTEGER NOT NULL DEFAULT '0',
  gnosis_dusk_score INTEGER NOT NULL DEFAULT '0',
  strife_dusk_score INTEGER NOT NULL DEFAULT '0',
  accumulated_bonus0 INTEGER NOT NULL DEFAULT '0',
  accumulated_bonus1 INTEGER NOT NULL DEFAULT '0',
  accumulated_bonus2 INTEGER NOT NULL DEFAULT '0',
  accumulated_bonus3 INTEGER NOT NULL DEFAULT '0',
  accumulated_bonus4 INTEGER NOT NULL DEFAULT '0',
  PRIMARY KEY  (id)
);
INSERT INTO seven_signs_status VALUES
(0,1,1,'COMPETITION',0,'NORMAL',0,0,0,0,'NORMAL','NORMAL','NORMAL',0,0,0,0,0,0,0,0,0,0,0);

-- ========== seven_signs.sql ==========
CREATE TABLE IF NOT EXISTS seven_signs (
  char_obj_id INT NOT NULL DEFAULT '0',
  cabal VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
  seal VARCHAR(8) NOT NULL DEFAULT 'NONE',
  red_stones INT NOT NULL DEFAULT '0',
  green_stones INT NOT NULL DEFAULT '0',
  blue_stones INT NOT NULL DEFAULT '0',
  ancient_adena_amount DECIMAL(20,0) NOT NULL DEFAULT '0',
  contribution_score DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY  (char_obj_id)
);
-- ========== heroes.sql ==========
CREATE TABLE IF NOT EXISTS heroes (
  char_id decimal(11,0) NOT NULL default '0',
  class_id decimal(3,0) NOT NULL default '0',
  count decimal(3,0) NOT NULL default '0',
  played decimal(1,0) NOT NULL default '0',
  active SMALLINT NOT NULL default 0,
  message varchar(300) NOT NULL default '',
  PRIMARY KEY  (char_id)
);
-- ========== heroes_diary.sql ==========
CREATE TABLE IF NOT EXISTS heroes_diary (
  char_id INTEGER NOT NULL,
  time BIGINT NOT NULL DEFAULT '0',
  action SMALLINT NOT NULL default '0',
  param INTEGER NOT NULL default '0'
);
-- ========== grandboss_list.sql ==========
CREATE TABLE IF NOT EXISTS grandboss_list (
  player_id decimal(11,0) NOT NULL,
  zone decimal(11,0) NOT NULL,
  PRIMARY KEY (player_id,zone)
);
-- ========== bbs_forum.sql ==========
CREATE TABLE IF NOT EXISTS bbs_forum (
  id INTEGER NOT NULL default '0',
  type VARCHAR(10) NOT NULL default '0',
  access VARCHAR(12) NOT NULL default '0',
  owner_id INTEGER NOT NULL default '0',
  UNIQUE (id)
);
-- ========== bbs_topic.sql ==========
CREATE TABLE IF NOT EXISTS bbs_topic (
  id INTEGER NOT NULL DEFAULT '0',
  forum_id INTEGER NOT NULL DEFAULT '0',
  name varchar(255) NOT NULL DEFAULT '',
  date decimal(20,0) NOT NULL DEFAULT '0',
  owner_name varchar(255) NOT NULL DEFAULT '0',
  owner_id INTEGER NOT NULL DEFAULT '0'
);
-- ========== bbs_post.sql ==========
CREATE TABLE IF NOT EXISTS bbs_post (
  id INTEGER NOT NULL DEFAULT '0',
  owner_name varchar(255) NOT NULL DEFAULT '',
  owner_id INTEGER NOT NULL DEFAULT '0',
  date decimal(20,0) NOT NULL DEFAULT '0',
  topic_id INTEGER NOT NULL DEFAULT '0',
  forum_id INTEGER NOT NULL DEFAULT '0',
  txt text NOT NULL
);
-- ========== bbs_mail.sql ==========
CREATE TABLE IF NOT EXISTS bbs_mail (
  id INT NOT NULL DEFAULT 0,
  receiver_id INT NOT NULL DEFAULT 0,
  sender_id INT NOT NULL DEFAULT 0,
  location VARCHAR(15) NOT NULL,
  recipients VARCHAR(200) DEFAULT NULL,
  subject VARCHAR(128) DEFAULT NULL,
  message VARCHAR(3000) DEFAULT NULL,
  sent_date TIMESTAMP NULL DEFAULT NULL,
  is_unread SMALLINT DEFAULT 1,
  PRIMARY KEY  (id)
);
-- ========== bbs_favorite.sql ==========
CREATE TABLE IF NOT EXISTS bbs_favorite (
  id INT NOT NULL DEFAULT 0,
  player_id INT NOT NULL DEFAULT 0,
  title VARCHAR(35) DEFAULT NULL,
  bypass VARCHAR(128) DEFAULT NULL,
  date TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY  (id)
);
-- ========== bbs_auction.sql ==========
CREATE TABLE IF NOT EXISTS bbs_auction (
	id INTEGER NOT NULL DEFAULT '0',
	obj_Id INTEGER NOT NULL DEFAULT '0',
	item_id INTEGER NOT NULL DEFAULT '0',
	item_count INTEGER NOT NULL DEFAULT '0',
	item_enchant INTEGER NOT NULL DEFAULT '0',
	price_id INTEGER NOT NULL DEFAULT '0',
	price_count INTEGER NOT NULL DEFAULT '0',
	duration BIGINT DEFAULT NULL,
	PRIMARY KEY (id)
);
-- ========== auctions.sql ==========
CREATE TABLE IF NOT EXISTS auctions (
	clanhall_id INT NOT NULL DEFAULT 0,
	bidder_name VARCHAR(35) NOT NULL DEFAULT '',
	clan_oid INT NOT NULL DEFAULT 0,
	clan_name VARCHAR(20) NOT NULL DEFAULT '',
	max_bid INT NOT NULL DEFAULT 0,
	time_bid BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (clanhall_id, clan_oid)
);
-- ========== buylists.sql ==========
CREATE TABLE IF NOT EXISTS buylists (
	buylist_id INT,
	item_id INT,
	count INT NOT NULL DEFAULT 0,
	next_restock_time BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (buylist_id, item_id)
);
-- ========== bookmarks.sql ==========
CREATE TABLE IF NOT EXISTS bookmarks (
  name VARCHAR(45) NOT NULL DEFAULT '',
  obj_Id INT NOT NULL DEFAULT '0',
  x INTEGER DEFAULT NULL,
  y INTEGER DEFAULT NULL,
  z INTEGER DEFAULT NULL,
  PRIMARY KEY (name, obj_Id)
);
-- ========== buffer_schemes.sql ==========
CREATE TABLE IF NOT EXISTS buffer_schemes (
  object_id INT NOT NULL DEFAULT '0',
  scheme_name VARCHAR(16) NOT NULL DEFAULT 'default',
  skills VARCHAR(200) NOT NULL,
  levels VARCHAR(200) NOT NULL,
  PRIMARY KEY (object_id, scheme_name)
);
-- ========== petition.sql ==========
CREATE TABLE IF NOT EXISTS petition (
  oid INT NOT NULL DEFAULT 0,
  type VARCHAR(20) NOT NULL,
  petitioner_oid INT NOT NULL DEFAULT 0,
  submit_date BIGINT NOT NULL DEFAULT 0,
  content VARCHAR(256) NOT NULL,
  is_unread SMALLINT NOT NULL DEFAULT 1,
  state VARCHAR(20) NOT NULL,
  rate VARCHAR(10) NOT NULL,
  feedback VARCHAR(512) NOT NULL,
  responders VARCHAR(150) NOT NULL,
  PRIMARY KEY  (oid)
);
-- ========== petition_message.sql ==========
CREATE TABLE IF NOT EXISTS petition_message (
  id INT NOT NULL DEFAULT 0,
  petition_oid INT NOT NULL DEFAULT 0,
  player_oid INT NOT NULL DEFAULT 0,
  type VARCHAR(20) NOT NULL,
  player_name VARCHAR(20) NOT NULL,
  content VARCHAR(120) NOT NULL,
  PRIMARY KEY  (id, petition_oid)
);
-- ========== fishing_championship.sql ==========
CREATE TABLE IF NOT EXISTS fishing_championship (
  player_name VARCHAR(35) NOT NULL,
  fish_length DOUBLE PRECISION NOT NULL,
  rewarded INTEGER NOT NULL
);
-- ========== games.sql ==========
CREATE TABLE IF NOT EXISTS games (
  id INT NOT NULL default 0,
  idnr INT NOT NULL default 0,
  number1 INT NOT NULL default 0,
  number2 INT NOT NULL default 0,
  prize  INT NOT NULL default 0,
  newprize  INT NOT NULL default 0,
  prize1  INT NOT NULL default 0,
  prize2  INT NOT NULL default 0,
  prize3  INT NOT NULL default 0,
  enddate decimal(20,0) NOT NULL default 0,
  finished INT NOT NULL default 0,
  PRIMARY KEY (id,idnr)
);
-- ========== mdt_bets.sql ==========
CREATE TABLE IF NOT EXISTS mdt_bets (
  lane_id INTEGER DEFAULT 0,
  bet INT DEFAULT 0,
  PRIMARY KEY (lane_id)
);
INSERT INTO mdt_bets VALUES
('1','0'),
('2','0'),
('3','0'),
('4','0'),
('5','0'),
('6','0'),
('7','0'),
('8','0');

-- ========== mdt_history.sql ==========
CREATE TABLE IF NOT EXISTS mdt_history (
  race_id INTEGER DEFAULT 0,
  first INTEGER DEFAULT 0,
  second INTEGER DEFAULT 0,
  odd_rate DOUBLE PRECISION DEFAULT 0,
  PRIMARY KEY (race_id)
);
-- ========== offline_trade.sql ==========
CREATE TABLE IF NOT EXISTS character_offline_trade_items (
  charId INTEGER NOT NULL,
  item INTEGER NOT NULL DEFAULT '0',
  count BIGINT NOT NULL DEFAULT '0',
  price BIGINT NOT NULL DEFAULT '0',
  enchant BIGINT NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS character_offline_trade (
  charId INTEGER NOT NULL,
  time BIGINT NOT NULL DEFAULT '0',
  type SMALLINT NOT NULL DEFAULT '0',
  title varchar(100) DEFAULT NULL,
  PRIMARY KEY (charId)
);
-- ========== mods_wedding.sql ==========
CREATE TABLE IF NOT EXISTS mods_wedding (
  id INT NOT NULL DEFAULT 0,
  requesterId INT NOT NULL DEFAULT 0,
  partnerId INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
-- ========== hwid.sql ==========
/*
 Navicat Premium Data Transfer

 Source Server         : servidor
 Source Server Type    : MariaDB
 Source Server Version : 110404
 Source Host           : 192.168.0.168:3306
 Source Schema         : 409

 Target Server Type    : MariaDB
 Target Server Version : 110404
 File Encoding         : 65001

 Date: 21/07/2025 22:53:05
*/


-- ----------------------------
-- Table structure for hwid_bans
-- ----------------------------
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS hwid_bans  (
  HWID varchar(32) NULL DEFAULT NULL,
  HWIDSecond varchar(32) NULL DEFAULT NULL,
  expiretime INTEGER NOT NULL DEFAULT 0,
  comments varchar(255) NULL DEFAULT '',
  CONSTRAINT hwid_bans_hwid_unique UNIQUE (HWID)
);

-- ----------------------------
-- Table structure for hwid_extra_boxes
-- ----------------------------
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS hwid_extra_boxes  (
  hwid varchar(64) NOT NULL,
  extra_boxes INTEGER NOT NULL,
  PRIMARY KEY (hwid)
);

-- ----------------------------
-- Table structure for hwid_info
-- ----------------------------
-- DROP TABLE disabled

CREATE TABLE IF NOT EXISTS hwid_info  (
  HWID varchar(32) NOT NULL DEFAULT '',
  Account varchar(45) NOT NULL DEFAULT '',
  PlayerID INTEGER NOT NULL DEFAULT 0,
  LockType VARCHAR(32) NOT NULL DEFAULT 'NONE',
  PRIMARY KEY (HWID)
);

-- ========== server_memo.sql ==========
CREATE TABLE IF NOT EXISTS server_memo (
  var VARCHAR(20) NOT NULL DEFAULT '',
  value VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (var)
);
-- ========== balance_classes.sql ==========
CREATE TABLE IF NOT EXISTS balance_classes (
	class_id_attacker INT NOT NULL,
	class_id_target INT NOT NULL,
	p_atk_mod DECIMAL(5,2) DEFAULT 1.00,
	m_atk_mod DECIMAL(5,2) DEFAULT 1.00,
	p_def_mod DECIMAL(5,2) DEFAULT 1.00,
	m_def_mod DECIMAL(5,2) DEFAULT 1.00,
	PRIMARY KEY (class_id_attacker, class_id_target)
);
-- ========== balance_vulnerability.sql ==========
CREATE TABLE IF NOT EXISTS balance_vulnerability (
    skill_type VARCHAR(50) NOT NULL PRIMARY KEY,
    multiplier DECIMAL(5,2) NOT NULL DEFAULT 1.00
);
INSERT INTO balance_vulnerability (skill_type, multiplier) VALUES
('BLEED', 1.00),
('POISON', 1.00),
('STUN', 1.00),
('PARALYZE', 1.00),
('ROOT', 1.00),
('SLEEP', 1.00),
('DERANGEMENT', 1.00),
('CONFUSION', 1.00),
('DEBUFF', 1.00),
('CANCEL', 1.00);

-- ========== events_custom_data.sql ==========
CREATE TABLE IF NOT EXISTS events_custom_data (
  event_name VARCHAR(35) NOT NULL,
  status decimal(1,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (event_name)
);
-- ========== rainbowsprings_attacker_list.sql ==========
CREATE TABLE IF NOT EXISTS rainbowsprings_attacker_list (
  clanId INT NOT NULL DEFAULT 0,
  war_decrees_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (clanId)
);
-- ========== donations_payments.sql ==========
CREATE TABLE IF NOT EXISTS donations_payments (
  purchase_id INT NOT NULL DEFAULT 0,
  mp_preference_id VARCHAR(52) DEFAULT NULL,
  paypal_invoice_id VARCHAR(25) DEFAULT NULL,
  qrcode TEXT DEFAULT NULL,
  link VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY (purchase_id)
);
-- ========== donations.sql ==========
CREATE TABLE IF NOT EXISTS donations (
  purchase_id INT NOT NULL DEFAULT 0,
  payment_id VARCHAR(30) DEFAULT NULL,
  payment_method VARCHAR(7) DEFAULT NULL,
  player_id INT NOT NULL DEFAULT 0,
  email VARCHAR(44) NOT NULL DEFAULT '',
  product_id INT NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 0,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency VARCHAR(3) DEFAULT NULL,
  date BIGINT DEFAULT 0,
  status VARCHAR(10) NOT NULL DEFAULT '',
  terms SMALLINT DEFAULT 0,
  PRIMARY KEY (purchase_id),
  UNIQUE (purchase_id, payment_id)
);
-- ========== autofarm_time_usage.sql ==========
CREATE TABLE IF NOT EXISTS autofarm_time_usage (
  player_id INTEGER NOT NULL,
  time_used BIGINT DEFAULT 0,
  last_reset TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id)
);
-- ----------------------------
-- Records 
-- ----------------------------

-- ========== autofarm_areas.sql ==========
CREATE TABLE IF NOT EXISTS autofarm_areas (
  player_id INT NOT NULL DEFAULT 0,
  area_id INT NOT NULL DEFAULT 0,
  name VARCHAR(44) DEFAULT NULL,
  type VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY (player_id, area_id)
);
-- ========== autofarm_skills.sql ==========
CREATE TABLE IF NOT EXISTS autofarm_skills (
  player_id INTEGER NOT NULL,
  skill_id INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  PRIMARY KEY (player_id,skill_id)
);
-- ----------------------------
-- Records 
-- ----------------------------

-- ========== autofarm_nodes.sql ==========
CREATE TABLE IF NOT EXISTS autofarm_nodes (
  node_id INT NOT NULL DEFAULT 0,
  area_id INT NOT NULL DEFAULT 0,
  loc_x INT NOT NULL DEFAULT 0,
  loc_y INT NOT NULL DEFAULT 0,
  loc_z INT NOT NULL DEFAULT 0,
  PRIMARY KEY (area_id, node_id)
);
-- ========== autofarm_player_data.sql ==========
CREATE TABLE IF NOT EXISTS autofarm_player_data (
  player_id INTEGER NOT NULL,
  time_used BIGINT DEFAULT 0,
  PRIMARY KEY (player_id)
);
-- ----------------------------
-- Records 
-- ----------------------------

-- ========== player_emails.sql ==========
CREATE TABLE IF NOT EXISTS player_emails (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  sender_id INTEGER NOT NULL,
  target_id INTEGER NOT NULL,
  email_id INTEGER NOT NULL,
  item_object_id INTEGER NOT NULL,
  item_id SMALLINT NOT NULL,
  count INTEGER NOT NULL,
  enchant_level SMALLINT NOT NULL,
  is_augmented SMALLINT NOT NULL DEFAULT 0,
  augment_id INTEGER DEFAULT NULL,
  is_paid SMALLINT NOT NULL DEFAULT 0,
  payment_item_id SMALLINT DEFAULT NULL,
  payment_item_count INTEGER DEFAULT NULL,
  status VARCHAR(32) DEFAULT 'PENDING',
  expiration_time BIGINT NOT NULL,
  created_time BIGINT NOT NULL,
  PRIMARY KEY (id)
);
-- ----------------------------
-- Records 
-- ----------------------------

-- ========== player_droplist_config.sql ==========
CREATE TABLE IF NOT EXISTS player_droplist_config (
    player_id INT NOT NULL,
    item_id INT NOT NULL,
    PRIMARY KEY (player_id, item_id)
);
-- ========== buffshop.sql ==========
CREATE TABLE IF NOT EXISTS buffshop (
  ownerId INTEGER NOT NULL,
  buffs text NOT NULL,
  title varchar(255) NOT NULL DEFAULT '',
  x INTEGER DEFAULT NULL,
  y INTEGER DEFAULT NULL,
  z INTEGER DEFAULT NULL,
  heading INTEGER DEFAULT NULL,
  tempBuffShopPrice varchar(32) DEFAULT NULL,
  store_message varchar(50) DEFAULT NULL,
  value varchar(64) DEFAULT NULL,
  class_id INTEGER NOT NULL DEFAULT 0,
  sex SMALLINT NOT NULL DEFAULT 0,
  face SMALLINT NOT NULL DEFAULT 0,
  hair_style SMALLINT NOT NULL DEFAULT 0,
  hair_color SMALLINT NOT NULL DEFAULT 0,
  equipped_items text DEFAULT NULL,
  PRIMARY KEY (ownerId)
);
-- ========== dungeon_cooldowns.sql ==========
CREATE TABLE IF NOT EXISTS dungeon_cooldowns (
    dungeon_id INT NOT NULL,
    player_id INT NOT NULL,
    last_join BIGINT NOT NULL,
    next_join BIGINT NOT NULL,
    ip_address VARCHAR(45),
	stage INT NOT NULL,
    PRIMARY KEY (dungeon_id, player_id)
);







