#!/usr/bin/env python3
"""Regenerate the canonical Flyway baseline from legacy tools/sql sources."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "tools/sql"
OUT = ROOT / "database/migrations"
MANIFEST = ROOT / "database/LEGACY_SQL_MANIFEST.txt"

EXCLUDE = {
    "donations_upgrade_legacy.sql",
    "donations_fix_pix.sql",
    "fix_player_emails_status.sql",
}

STRIP_DML = {
    "autofarm_player_data.sql",
    "autofarm_skills.sql",
    "autofarm_time_usage.sql",
    "player_emails.sql",
    "gameservers.sql",
}

ORDER = [
    ["accounts.sql", "account_premium.sql", "gameservers.sql"],
    ["characters.sql"],
    [p.name for p in SQL_DIR.glob("character_*.sql")],
    ["items.sql", "items_on_ground.sql", "pets.sql", "augmentations.sql", "cursed_weapons.sql"],
    [p.name for p in SQL_DIR.glob("clan*.sql")],
    [p.name for p in SQL_DIR.glob("castle*.sql")],
    [p.name for p in SQL_DIR.glob("clanhall*.sql")],
    ["siege_clans.sql", "spawn_data.sql"],
    [p.name for p in SQL_DIR.glob("olympiad*.sql")],
    [p.name for p in SQL_DIR.glob("seven_signs*.sql")],
    ["heroes.sql", "heroes_diary.sql", "grandboss_list.sql"],
    [p.name for p in SQL_DIR.glob("bbs_*.sql")],
    ["auctions.sql", "buylists.sql", "bookmarks.sql", "buffer_schemes.sql"],
    [
        "petition.sql",
        "petition_message.sql",
        "fishing_championship.sql",
        "games.sql",
        "mdt_bets.sql",
        "mdt_history.sql",
    ],
    ["offline_trade.sql", "mods_wedding.sql", "hwid.sql", "server_memo.sql"],
    [
        "balance_classes.sql",
        "balance_vulnerability.sql",
        "events_custom_data.sql",
        "rainbowsprings_attacker_list.sql",
    ],
    [p.name for p in SQL_DIR.glob("donation*.sql")],
    [p.name for p in SQL_DIR.glob("autofarm*.sql")],
    [p.name for p in SQL_DIR.glob("player_*.sql")],
    ["buffshop.sql", "dungeon_cooldowns.sql"],
]


def ordered_files() -> list[Path]:
    seen: set[str] = set()
    ordered: list[Path] = []
    for bucket in ORDER:
        for name in bucket:
            if name in EXCLUDE or name in seen:
                continue
            p = SQL_DIR / name
            if p.exists():
                ordered.append(p)
                seen.add(name)
    for p in sorted(SQL_DIR.glob("*.sql")):
        if p.name not in seen and p.name not in EXCLUDE:
            ordered.append(p)
            seen.add(p.name)
    return ordered


def transform(name: str, body: str) -> str:
    body = re.sub(r"(?im)^\s*USE\s+\w+\s*;\s*$", "", body)
    body = re.sub(r"(?im)^\s*SET\s+FOREIGN_KEY_CHECKS\s*=\s*\d+\s*;\s*$", "", body)
    body = re.sub(r"(?im)^\s*SET\s+NAMES\b.*$", "", body)
    body = re.sub(r"(?im)^\s*DROP\s+TABLE\b[^;]*;", "-- DROP TABLE disabled\n", body)
    body = re.sub(r"(?i)CREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)", "CREATE TABLE IF NOT EXISTS ", body)
    if name in STRIP_DML:
        parts = re.split(r"(?i)(?=CREATE\s+TABLE)", body)
        keeps: list[str] = []
        for part in parts:
            if re.match(r"(?i)\s*CREATE\s+TABLE", part):
                m = re.search(r"(?i)\b(INSERT|REPLACE|UPDATE|ALTER)\b", part)
                if m:
                    part = part[: m.start()]
                keeps.append(part.rstrip() + "\n")
        body = "\n".join(keeps)
    # Idempotent seed data: re-running baseline on an existing DB must not fail on PK dups.
    body = re.sub(r"(?im)^\s*REPLACE\s+INTO\b", "-- REPLACE INTO disabled", body)
    body = re.sub(
        r"(?i)\bINSERT\s+(?!IGNORE\s+)INTO\b",
        "INSERT IGNORE INTO",
        body,
    )
    return body.strip()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    ordered = ordered_files()
    parts = [
        "-- BrProject Phase 5 Flyway baseline (clean)\n",
        f"-- Source files: {len(ordered)} (excluded dumps/upgrades)\n",
        "-- Regenerated by tools/generate_flyway_migrations.py\n\n",
    ]
    for p in ordered:
        parts.append(f"\n-- ========== {p.name} ==========\n")
        parts.append(transform(p.name, p.read_text(encoding="utf-8", errors="replace")))
        parts.append("\n")
    baseline = OUT / "V1.0.0__baseline_schema.sql"
    baseline.write_text("".join(parts), encoding="utf-8")
    MANIFEST.write_text("\n".join(p.name for p in ordered) + "\n", encoding="utf-8")
    print(f"wrote {baseline} ({baseline.stat().st_size} bytes) from {len(ordered)} files")
    print("excluded:", ", ".join(sorted(EXCLUDE)))


if __name__ == "__main__":
    main()
